name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Rust & Cargo - AoC
        working-directory: 2021/day10_rust/day10
        run: |
          cargo check
          cargo test
          cargo run input.txt

      - name: Rust & Cargo - Hello World
        working-directory: rust_test/hello_cargo
        run: |
          cargo check
          cargo build
          cargo run

          cargo build --release
          cargo run

      - name: Prepare build directory
        run: |
          mkdir -p build

      - name: Configure CMake
        run: |
          pushd build
          cmake ..
          make -j4
          popd

      - name: Test
        run: |
          pushd build
          ctest --verbose
          popd
