name: CI

on:
  push:
    branches: [master, feat/chfo/220222_cmake]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Configure CMake
        run: |
          mkdir -p build
          pushd build
          cmake ..
          make -j4
          ctest -j4
          popd

      - name: Test
        run: |
          pushd build
          ctest -j4
          popd
