name: CI

on:
  push:
    branches: [master, 2022_day10]
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  INPUT_7Z_PASSWORD: ${{github.INPUT_7Z_PASSWORD}}
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Prepare secrets
        working-directory: 2022/rust
        run: |
          $pwd
          export INPUT_7Z_PASSWORD=${{github.INPUT_7Z_PASSWORD}}
          bash extract_secrets.sh

      - name: Rust & Cargo - AoC 2021
        working-directory: 2021/day10_rust/day10
        run: |
          cargo check
          cargo test
          cargo run input.txt

      - name: Rust & Cargo - AoC 2022 day 1
        working-directory: 2022/rust/day1
        run: cargo check && cargo test && cargo run input.txt

      - name: Rust & Cargo - AoC 2022 day 2
        working-directory: 2022/rust/day2
        run: cargo check && cargo test && cargo run input.txt

      - name: Rust & Cargo - AoC 2022 day 3
        working-directory: 2022/rust/day3
        run: cargo check && cargo test && cargo run input.txt

      - name: Rust & Cargo - AoC 2022 day 4
        working-directory: 2022/rust/day4
        run: cargo check && cargo test && cargo run input.txt        

      - name: Rust & Cargo - AoC 2022 day 5
        working-directory: 2022/rust/day5
        run: cargo check && cargo test && cargo run input.txt

      - name: Rust & Cargo - AoC 2022 day 6
        working-directory: 2022/rust/day6
        run: cargo check && cargo test && cargo run input.txt     

      - name: Rust & Cargo - AoC 2022 day 7
        working-directory: 2022/rust/day7
        run: cargo check && cargo test && cargo run input.txt                          

      - name: Rust & Cargo - AoC 2022 day 8
        working-directory: 2022/rust/day8
        run: cargo check && cargo test && cargo run input.txt           

      - name: Rust & Cargo - AoC 2022 day 9
        working-directory: 2022/rust/day9
        run: cargo check && cargo test && cargo run input.txt           


      - name: Prepare build directory (AoC C++)
        run: |
          mkdir -p build

      - name: Configure CMake (AoC C++)
        run: |
          pushd build
          cmake ..
          make -j4
          popd

      - name: Test (AoC C++)
        run: |
          pushd build
          ctest --verbose
          popd
